### ISSUE TITLE
'Node' object has no attribute '_Entity__remote'

### ISSUE THREAD

**Issue by abhinavk1492** [elementsinteractive/flask-graphql-neo4j#4]
Whenever I am trying to query a customer with related store names, I am getting the following error:

**Request:**
```
{
  customer(email:"charles@gmail.com"){
    name,
    email,
    stores{
      name
    }
  }
}
```

**Response:**
```
{
  "errors": [
    {
      "message": "'Node' object has no attribute '_Entity__remote'",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "customer",
        "stores"
      ]
    }
  ],
  "data": {
    "customer": {
      "name": "Charles",
      "email": "charles@gmail.com",
      "stores": null
    }
  }
}
```

What am I doing wrong?

**Comment by streeck** [comment]
Hi @abhinavk1492, sorry for the late response on this, are you still facing this issue?

Could you walk me through the steps you've followed and the `Pipfile.lock` that you have locally?

**Comment by streeck** [comment]
I'm closing this issue for now as @abhinavk1492 has not replied.
