### ISSUE TITLE
Docker-compose fails

### ISSUE THREAD

**Issue by mfkilgore** [elementsinteractive/flask-graphql-neo4j#7]
I  downloaded the project and ran 'docker-compose up' and have the following error (missing dependencies?).  Not sure how to resolve. I am running  mac os catalina 10.15.2, with latest docker desktop.

Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting pendulum==2.0.5', '  Using cached https://files.pythonhosted.org/packages/e0/f9/ea90c2c8f0d9b6a733f6231fac6d07476b68271bcf02bab0053888ea0fb3/pendulum-2.0.5.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'error'"]

**Comment by streeck** [comment]
I'll have a look at this tomorrow or the day after, seems to be pipenv related though.
Given this [issue](https://github.com/pypa/pipenv/issues/4058) at pipenv's repo it might be a good idea to change the approach when dealing with this repo's dependencies. I'll also consider that, let me know in the meantime if you happen to have any progress!

**Comment by mfkilgore** [comment]
I have not had a chance to get back to this, but I believe you are correct it is is pipenv causing the problem here. Maybe going back to simple requirements.txt??  If I get a chance I will try to simplify.

Thanks

**Comment by joeymbryan** [comment]
I was curious about this as well, has anyone been able to figure out this error?

**Comment by streeck** [comment]
Hey, @joeymbryan and @mfkilgore, I'm sorry for the long time to look into this 🙈.

I've finally managed to have a look though and It's not related to pipenv but not having openssl and libffi in the docker image.
I conjecture that one of the indirect dependencies (which are not pinned for some reason 🤔) started using those c libraries under the hood and now they are needed in the Dockerfile. I've tested the changes locally and they seem to fix the problem.
I'll also open a separate PR though to remove Pipenv and use Poetry together with pure requirements.txt.

I'll have a PR in a moment, could you guys test it out and let me know if everything's working fine? After that I can close this ticket 😄.

**Comment by joeymbryan** [comment]
That worked @streeck thanks!

**Comment by streeck** [comment]
Great to hear @joeymbryan, I'll close this issue for now then, thanks for testing it out!
